export default function MyExperiences() {
  return [
    {
      topic: "Founder & Tutor",
      company: "UThink",
      startYear: "05/2024",
      endYear: "Current",
      description: "",
      image: "/experience/uthink.png",
      link: "",
      linkDisplay: "unavailable",
    },
    {
      topic: "Project Manager",
      company: "Software Enginering Subject Project",
      startYear: "03/2024",
      endYear: "04/2024",
      description: "",
      image: "/experience/software-engineering-cgr-project.png",
      link: "https://software-engineering-cgr-project-frontend.vercel.app/",
      linkDisplay: "software-engineering-cgr.vercel.app",
    },
    {
      topic: "Founder & CEO",
      company: "MindLink Tupay",
      startYear: "03/2024",
      endYear: "Current",
      description: "",
      image: "/experience/mindlink-tupay.png",
      link: "",
      linkDisplay: "unavailable",
    },
    {
      topic: "Relation and Marketing expert",
      company: "OpenMirai",
      startYear: "02/2023",
      endYear: "Current",
      description: "",
      image: "/experience/openmirai.png",
      link: "https://www.openmirai.com/",
      linkDisplay: "openmirai.com",
    },
    {
      topic: "Computer and Mathematics Tutor",
      company: "#include tutor.s",
      startYear: "12/2022",
      endYear: "05/2024",
      description: "",
      image: "/experience/include-tutor-s.png",
      link: "https://www.facebook.com/profile.php?id=61553974435444",
      linkDisplay: "facebook.com",
    },
    {
      topic: "Consultant of Student Council",
      company: "PCSHS Chonburi School",
      startYear: "08/2022",
      endYear: "02/2023",
      description: "",
      image: "/experience/pcshs-chonburi-school.png",
      link: "https://instagram.com/pcshschon.sc/",
      linkDisplay: "instagram.com",
    },
  ];
}
