export default function MyExperiences() {
  return [
    {
      topic: "Founder & Tutor",
      company: "UThink",
      startYear: "05/2024",
      endYear: "Current",
      description: "",
      image: "",
      link: "",
      linkDisplay: "unavailable",
    },
    {
      topic: "Project Manager of University Subject Project",
      company: "Chulalongkorn University (Software Management System)",
      startYear: "03/2024",
      endYear: "04/2024",
      description: "",
      image: "",
      link: "",
      linkDisplay: "Project Link",
    },
    {
      topic: "Founder & CEO",
      company: "MindLink Tupay",
      startYear: "03/2024",
      endYear: "Current",
      description: "",
      image: "",
      link: "",
      linkDisplay: "unavailable",
    },
    {
      topic: "Relation and Marketing expert",
      company: "OpenMirai",
      startYear: "02/2023",
      endYear: "Current",
      description: "",
      image: "",
      link: "https://www.openmirai.com/",
      linkDisplay: "openmirai.com",
    },
    {
      topic: "Computer and Mathematics Tutor",
      company: "# inclide tutor.s",
      startYear: "12/2022",
      endYear: "05/2024",
      description: "",
      image: "",
      link: "https://www.facebook.com/profile.php?id=61553974435444",
      linkDisplay: "facebook.com",
    },
    {
      topic: "Consultant of Student Council",
      company: "PCSHS Chonburi School",
      startYear: "08/2022",
      endYear: "02/2023",
      description: "",
      image: "",
      link: "https://instagram.com/pcshschon.sc/",
      linkDisplay: "instagram.com",
    },
  ];
}
