export default function MyProjects() {
  return [
    {
      year: "Year 2024",
      data: [
        {
          topic: "DIW Lab Platform",
          organization: "Department of Industrial Works",
          startYear: "06/2024",
          endYear: "Current",
          codingLang: ["Next.js", "TailwindCSS", "Node.js"],
          role: ["Frontend Developer", "Designer"],
          description:
            "The system is designed to help the Department of Industrial Works (DIW) manage and monitor their laboratory equipment. It provides a comprehensive view of all equipment, including details such as the equipment name, model, and status. Users can easily search for specific equipment, view detailed information, and update the status of each item. The system also generates reports on equipment usage and maintenance, helping DIW optimize their resources and ensure equipment is well-maintained. As a front-end developer and designer, I ensured the system is user-friendly and visually appealing, providing a seamless experience for DIW staff.",
          image: [
            "/project/diw-lab-platform-0.png",
            "/project/diw-lab-platform-1.png",
            "/project/diw-lab-platform-2.png",
            "/project/diw-lab-platform-3.png",
          ],
          link: "https://lab-platform.diw.go.th/",
          status: "In progress",
        },
        {
          topic: "Summy Share (SKS)",
          organization: "Personal Project",
          startYear: "10/2024",
          endYear: "10/2024",
          codingLang: ["Next.js", "TailwindCSS", "MongoDB", "Node.js"],
          role: ["Full-stack Developer", "Designer"],
          description:
            "The Survival kit store is the platform that sell summaries for university students. The platform allows users to purchase summaries for various subjects, with each summary containing detailed notes, diagrams, and explanations. The platform is designed to be user-friendly and intuitive, providing a seamless experience for both buyers and sellers. As a full-stack developer and designer, I ensured the system is visually appealing and functional, delivering a valuable resource for university students.",
          image: [
            "/project/sks-0.png",
            "/project/sks-1.png",
            "/project/sks-2.png",
          ],
          link: "https://survival-kit-store.vercel.app/",
          status: "Done",
        },
        {
          topic: "MindLink System",
          organization: "MindLink",
          startYear: "08/2024",
          endYear: "Current",
          codingLang: [
            "Next.js",
            "TailwindCSS",
            "ProstgreSQL",
            "Express.js",
            "Node.js",
          ],
          role: ["CEO", "Project Manager", "Designer"],
          description:
            "The system helps tutors efficiently and securely organize payments and manage students. Users can create organizations within the system, each accommodating multiple roles such as teachers, accountants, and administrators. Users can also create new classes to organize students, with each class containing payment details such as the payment amount and due date. The system allows parents to make payments using a Line bot, which automatically checks and validates receipts, displaying the data to the organization. As the CEO and Project Manager, I established the overall structure and contributed as a full-stack developer, ensuring the system effectively reduces the time tutors spend on managing student payments and organization.",
          image: [
            "/project/mindlink-0.png",
            "/project/mindlink-1.png",
            "/project/mindlink-2.png",
            "/project/mindlink-3.png",
            "/project/mindlink-4.png",
            "/project/mindlink-5.png",
            "/project/mindlink-6.png",
            "/project/mindlink-7.png",
          ],
          link: "",
          status: "In progress",
        },
        {
          topic: "LineBot Message Manager",
          organization: "SCG | Prompt Dee & Rakmao",
          startYear: "06/2024",
          endYear: "08/2024",
          codingLang: ["Next.js", "TailwindCSS", "MongoDB", "Node.js"],
          role: ["Designer", "Full-stack Developer"],
          description:
            "The LineBot Message Manager is a web-based application developed for SCG to manage and fully customize flex messages sent by LineBot. The system provides a comprehensive view of all messages, including saving flex messages, tracking user interactions, and generating custom Excel templates. It also offers detailed analytics, such as the number of users who clicked or replied to messages. This data is vital for SCG to evaluate the effectiveness of their LineBot campaigns and optimize future messaging strategies. As a designer and full-stack developer, I ensured the system is user-friendly and delivers valuable insights to help SCG enhance their LineBot messaging performance.",
          image: [
            "/project/linebot-message-manager-0.png",
            "/project/linebot-message-manager-1.png",
            "/project/linebot-message-manager-2.png",
          ],
          link: "",
          status: "Done",
        },
        {
          topic: "Friday Act System",
          organization: "Chula Engineering",
          startYear: "06/2024",
          endYear: "Current",
          codingLang: [
            "Next.js",
            "TailwindCSS",
            "ProstgreSQL",
            "Express.js",
            "Node.js",
          ],
          role: ["Project Manager", "Designer"],
          description:
            "Friday Act System is a web-based application developed for CEDT at Chula Engineering to facilitate easier student activity applications. The system supports two roles: student and admin. Admins can create company profiles and activities associated with those companies. It also tracks each student's activity application history. The attendance function uses QR codes to validate student participation in the activities they applied for, ensuring accurate attendance records. This comprehensive data management provides a seamless and efficient experience for both admins and students. As the Project Manager, I established the overall structure and contributed as a full-stack developer, ensuring the system is user-friendly and meets the needs of all users.",
          image: [
            "/project/friday-act-system-0.png",
            "/project/friday-act-system-1.png",
            "/project/friday-act-system-2.png",
            "/project/friday-act-system-3.png",
          ],
          link: "",
          status: "In progress",
        },
        {
          topic: "MindLink Prototype",
          organization: "MindLink",
          startYear: "06/2024",
          endYear: "08/2024",
          codingLang: [
            "Next.js",
            "TailwindCSS",
            "MongoDB",
            "Express.js",
            "Node.js",
          ],
          role: ["CEO", "Project Manager", "Full-stack Developer", "Designer"],
          description:
            "The system helps tutors efficiently and securely organize payments and manage students. Users can create organizations within the system, each accommodating multiple roles such as teachers, accountants, and administrators. Users can also create new classes to organize students, with each class containing payment details such as the payment amount and due date. The system allows parents to make payments using a Line bot, which automatically checks and validates receipts, displaying the data to the organization. As the CEO and Project Manager, I established the overall structure and contributed as a full-stack developer, ensuring the system effectively reduces the time tutors spend on managing student payments and organization.",
          image: [
            "/project/mindlink-tupay-0.png",
            "/project/mindlink-tupay-1.png",
            "/project/mindlink-tupay-2.png",
            "/project/mindlink-tupay-3.png",
            "/project/mindlink-tupay-4.png",
            "/project/mindlink-tupay-5.png",
          ],
          link: "",
          status: "Done",
        },
        {
          topic: "Commanders Gambit",
          organization: "Cross work @ Chula",
          startYear: "05/2024",
          endYear: "06/2024",
          codingLang: ["Java", "JavaFX"],
          role: ["Game Designer", "Game Logic Developer"],
          description:
            "The PC application is a base game where players command their military, featuring two modes: Single Player and Two Player. At the start, a 25 x 25 map of terrains is randomly generated, including Land, Highland, Water, Bridge, and Town, each offering unique buffs and abilities. Players begin with various units: 1 Ship, 1 Destroyer Tank, 1 Heavy Tank, 2 Medium Tanks, 2 Light Tanks, 1 Sniper Soldier, 3 Heavy Soldiers, and 6 Normal Soldiers, each with distinct stats and skills such as activating a shield or grouping with another soldier. The objective is to defeat the opposing team, achieved either by eliminating all enemy units or invading the enemy's town. Each turn, players have 25 mana to perform actions, with the system providing assistance by identifying targets within range and finding the most efficient paths, making gameplay more intuitive. I organized the project, set up the structure of the application, and worked on all of the algorithms, ensuring a smooth and engaging gameplay experience.",
          image: [
            "/project/commanders-gambit-0.png",
            "/project/commanders-gambit-1.png",
          ],
          link: "",
          status: "Done",
        },
        {
          topic: "Campground Reservation",
          organization: "Cross work @ Chula",
          startYear: "04/2024",
          endYear: "06/2024",
          codingLang: [
            "Next.js",
            "TailwindCSS",
            "MongoDB",
            "Express.js",
            "Node.js",
          ],
          role: ["Project Manager", "Full-stack Developer"],
          description:
            "The web-based application allows users to reserve campgrounds efficiently. The system features a comprehensive database of campgrounds and individual campground sites, each with a unique area number and dimensions. Users can easily check the availability of a campground site for specific dates and make reservations, with a maximum of three pre-reserves per user. Additionally, the system empowers campground owners to create and promote their campgrounds. As the Scrum Master and Project Manager, I oversaw the project, established the frontend and database structure, and contributed as a full-stack developer, ensuring a seamless and user-friendly experience for both campers and campground owners.",
          image: [
            "/project/campground-reservation-system-0.png",
            "/project/campground-reservation-system-1.png",
            "/project/campground-reservation-system-2.png",
            "/project/campground-reservation-system-3.png",
            "/project/campground-reservation-system-4.png",
          ],
          link: "https://software-engineering-cgr-project-frontend.vercel.app/",
          status: "Done",
        },
      ],
    },
    {
      year: "Year 2023",
      data: [
        {
          topic: "JLControl Website",
          organization: "JLControl",
          startYear: "2023",
          endYear: "2023",
          codingLang: ["React", "Bootstrap"],
          role: ["Front-End Developer"],
          description:
            "The website is designed to showcase projects and provide information about JLControl.co. It encompasses all relevant company details, including an 'about us' section, contact information, and a portfolio of projects. It's a static webpage built with HTML, CSS, and JavaScript. As a designer and front-end developer, my role involves crafting the visual and interactive elements of the site, ensuring a seamless user experience while effectively communicating JLControl.co's brand and services.",
          image: [
            "/project/jlcontrol-website-0.png",
            "/project/jlcontrol-website-1.png",
            "/project/jlcontrol-website-2.png",
          ],
          link: "https://www.jlcontrol.com/#/th",
          status: "Done",
        },
        {
          topic: "CEDT Library",
          organization: "Cross work @ Chula",
          startYear: "2023",
          endYear: "2023",
          codingLang: [
            "HTML",
            "CSS",
            "JavaScript",
            "MongoDB",
            "Express.js",
            "Node.js",
          ],
          role: ["Front-End Developer"],
          description:
            "The website is designed for CEDT students to communicate anonymously. It allows users to chat with each other in groups, functioning similarly to an open chat system. The user interface is designed to be friendly and suitable for students. The system includes features like 'like' and 'report' options for messages to ensure a safe and positive community environment. As a front-end developer, my role involves creating an intuitive and engaging user experience to facilitate seamless interaction among students.",
          image: ["/project/cedt-library-0.png"],
          link: "",
          status: "Done",
        },
      ],
    },
    {
      year: "Year 2022",
      data: [
        {
          topic: "Mimir Project",
          organization: "Club @ PCSHS Chonburi",
          startYear: "2022",
          endYear: "2023",
          codingLang: ["HTML", "CSS", "Bootstrap", "PHP", "MySQL"],
          role: ["Project Manager", "Full-stack Developer", "Instructor"],
          description:
            "This project is designed to enhance the capabilities of participants preparing for the POSN examination over a period of two months, covering all five major subjects. I am responsible for the computer science subject as well as overseeing the entire project. The training program includes 452 participants, and I serve as the founder and instructor for the computer science component, providing a total of 30 hours of instruction. In addition to teaching, I am also in charge of organizing and conducting guidance activities to ensure that participants receive comprehensive support throughout the training period.",
          image: [
            "/project/mimir-project-0.png",
            "/project/mimir-project-1.png",
            "/project/mimir-project-2.png",
            "/project/mimir-project-3.png",
          ],
          link: "",
          status: "Done",
        },
      ],
    },
    {
      year: "Year 2021",
      data: [
        {
          topic: "Project Classroom",
          organization: "Cross work @ PCSHS",
          startYear: "2021",
          endYear: "2022",
          codingLang: [
            "HTML",
            "CSS",
            "Bootstrap",
            "JavaScript",
            "PHP",
            "MySQL",
          ],
          role: ["Project Manager", "Full-stack Developer", "Designer"],
          description:
            "Project Classroom is a web-based application designed to enhance the connection and interaction between students and teachers. It offers a comprehensive set of tools that help teachers manage their students, assignments, and file sharing efficiently. Teachers can easily distribute assignments, upload resources, and track student progress through the platform. On the other hand, students benefit from a streamlined process for submitting assignments, downloading necessary files, and maintaining clear communication with their teachers. By centralizing these essential academic functions, Project Classroom fosters a more organized and collaborative educational environment, ultimately enhancing the learning experience for both students and teachers.",
          image: [
            "/project/project-classroom-0.png",
            "/project/project-classroom-1.png",
            "/project/project-classroom-2.png",
          ],
          link: "",
          status: "Done",
        },
        {
          topic: "Package Tracker",
          organization: "PCSHS Student Affairs Department",
          startYear: "2021",
          endYear: "2022",
          codingLang: ["HTML", "CSS", "Bootstrap", "PHP", "MySQL"],
          role: ["Full-stack Developer"],
          description:
            "Package Tracker is a web-based application designed to help students at my school track their packages. When I was in boarding school, my friends frequently ordered items online and had them shipped to the school. This inspired the idea for the Package Tracker system. Users can track their packages by entering their name, and the system will display the package's status. Additionally, teachers who manage the packages can update and monitor the status to ensure that packages are properly handled and accounted for.",
          image: ["/project/package-tracker-0.png"],
          link: "",
          status: "Done",
        },
      ],
    },
  ];
}
