export default function MyStory() {
  return [
    "I developed an interest in programming when I was 13. The first thing I learned was the Popx2 robot. That was when I decided to embark on my programming journey. I remember my first competition was the WRO 2019. At that time, I was new to coding and, unsurprisingly, didn’t win any awards. However, that competition was like a guiding star for me. I dedicated a lot of time to learning and understanding programming logic.",
    "At 16, I started teaching myself C programming. I loved solving problems and planned my journey to learn more about mathematics and computer science. When I was 17, I got into the second camp of POSN (The Promotion of Academic Olympiad and Development of Science Education Foundation). There, I learned a lot about data structures, algorithms, computing structures, time complexity, and more. I worked hard to understand these concepts and realized I was delving deeply into real programming.",
    "After finishing the POSN camp, I explored another path in programming: web development. I started with the basics, such as HTML, CSS, and JavaScript. My first backend language was PHP. My first website project, “Project Classroom,” may not have been perfect, but it looked good to me. That project won a gold medal at the Science Symposium. I then improved my skills by working on projects for my school.",
    "After graduating from high school, I wanted to give back to my school. So, I started the “Mimir Project” to enhance students' knowledge and prepare them for POSN competitions. The project provided tutoring in five subjects: Math, Biology, Chemistry, Physics, and Computer Science, all for free. It included pre-exams, tutoring sessions, and seminars. I was the project manager and created the promotional and application form website.",
    "Today, I’m studying Computer Engineering at Chulalongkorn University. I am learning new programming frameworks like React and Next.js and continually working to improve my programming and management skills. I have also started my own company, “MindLink Tupay,” which helps tutors manage students and payments more easily. This journey has been thrilling, and I can't wait to see what the future holds.",
  ]
}
